### ISSUE TITLE
Additional Datasets

### ISSUE THREAD

**Issue by rebeccabilbro** [DistrictDataLabs/yellowbrick#60] opened 2016-10-06 16:53 UTC
Need to get some additional datasets for testing. We currently have two classification datasets and one regression one. We need: 
- at least one more regression dataset
- at least one more classification dataset that's not a binary classification.

**Comment by rebeccabilbro** [comment] 2016-10-06 16:55
Maybe the mushroom dataset for multi-class?

**Comment by bbengfort** [comment] 2016-10-06 17:01
Mushroom data set would be a good one; and hopefully in the user testing we
get a few as well.
>
>

-- 
Sent from Gmail Mobile

**Comment by hboyan** [comment] 2016-10-10 17:13
Do you have any guidelines on the features you want included in these, or the number of observations? I have tons of datasets kicking around that I've used for my students to practice on, so they're fairly straightforward/clean. Would love to help!

**Comment by bbengfort** [comment] 2016-10-10 19:18
@hboyan one thing that we're looking for that you might be able to give advice on is data sets that have interesting feature analysis and modeling constraints; for example a dataset that is better for LASSO than Ridge _and_ vice versa; or a data set that is better for Bayesian modeling than logistic regression (and vice versa). Basically - raw data sets that require some feature, model, and hyperparameter analysis that we can use to demonstrate the efficacy of visual diagnostics and conduct a user study to demonstrate that visual diagnostics are faster than non-visual and potentially even search based method.

**Comment by bbengfort** [comment] 2017-03-07 18:15
@rebeccabilbro ok, we've added the energy dataset for regression, and mushroom for multiclass (though I thought that was poisonous vs. not poisonous?). I think we need to add one more multiclass with > 5 classes. 

I'm going to add this to in progress to mark that it's underway, and I can quickly add the last data set, when we've decided.

**Comment by NealHumphrey** [comment] 2017-03-07 18:19
@bbengfort the data set that I used as a basis for choosing the ConfusionMatrixVisualizer came out of the sklearn handwritten digits dataset. The music dataset I started out using as an example is kind of messy, so I was planning to convert my example over to the digits example. That might be a good one to use for a multi-class classifier example? It's nice because it's 10 classes, a good balance of big but not too big, and some nice overlap of some easy-to-identify and hard-to-identify classes.

**Comment by bbengfort** [comment] 2017-03-07 18:31
@NealHumphrey -- that's a good one, but I'd like to have our own examples just so we can show something slightly different from scikit-learn. 

What about predicting religion from country flags? 
http://archive.ics.uci.edu/ml/datasets/Flags

This will require transformers, which would also help us evaluate the YB workload. The problem is that it requires transformers (the categorical data).

**Comment by rebeccabilbro** [comment] 2017-03-31 19:23
Ok, some suggestions:

For classification (multi-class)
 - [Connect four data](https://archive.ics.uci.edu/ml/datasets/Connect-4) (target can be Win, Lose, or Draw)
 - [Flags](http://archive.ics.uci.edu/ml/datasets/Flags) (target can be 0=Catholic, 1=Other Christian, 2=Muslim, 3=Buddhist, 4=Hindu, 5=Ethnic, 6=Marxist, 7=Others)

For regression
 - [Songs by year](https://archive.ics.uci.edu/ml/datasets/YearPredictionMSD) (target is a year between 1922 and 2011)
 - [Daily bikeshare rentals](https://archive.ics.uci.edu/ml/datasets/Bike+Sharing+Dataset) (target is the number of bikes rented on a given day)

For clustering
 - [SMS spam](https://archive.ics.uci.edu/ml/datasets/SMS+Spam+Collection)
 - [DOW Jones data](https://archive.ics.uci.edu/ml/datasets/Dow+Jones+Index)

**Comment by rebeccabilbro** [comment] 2017-04-05 22:42
@bbengfort can you please review?

**Comment by bbengfort** [comment] 2017-05-04 16:28
@rebeccabilbro ok, so I added the connect four and bike share data (and added mushroom a while ago). The other suggestions were good, unfortunately it wasn't easy to transform them into a format that yellowbrick could use. 

We've got a few datasets and between these and the dataset generators in scikit-learn I'd say we're covered. I'm going to close this issue, but we can create more dataset issues as needed.

**Closed** 2017-05-04 16:28 UTC
Labels: level: novice, priority: high, review, type: task
