### ISSUE TITLE
Typo in class_prediction_error imports in v1.2

### ISSUE THREAD

**Issue by cokowpublic** [DistrictDataLabs/yellowbrick#1133] opened 2020-12-17 05:47 UTC
Typo:

Import error w/ SilhouetteVisualizer tracked to typo in class_prediction_error.py -- line 24 reads:
from sklearn.metrics._classification import _check_targets
and should read
from sklearn.metrics.classification import _check_targets

**Comment by rebeccabilbro** [comment] 2020-12-17 13:44
Hello and thanks for checking out Yellowbrick!

The `sklearn.metrics.classification` module was deprecated in `sklearn` v0.22, so we have updated our package to import from `sklearn.metrics._classification` instead.

Try updating your version of `scikit-learn` (e.g. `pip install -U scikit-learn>=0.22` or `conda install scikit-learn>=0.22`) and see if that helps!

In the next release of Yellowbrick, [we do a bit of additional handling to address the case where users have older versions of scikit-learn](https://github.com/DistrictDataLabs/yellowbrick/pull/1124).

_Duplicate of #1122_

**Closed by rebeccabilbro** 2020-12-17 13:44 UTC
