### ISSUE TITLE
No target coloring in jointplot

### ISSUE THREAD

**Issue by ZhiliangWu** [DistrictDataLabs/yellowbrick#1125] opened 2020-10-26 14:13 UTC
**Describe the bug**
After assigning `y` values in the `fit()` method of `JointPlot`, no heatmap of such target is drawn on the samples

**To Reproduce**

```python
import numpy as np
from yellowbrick.features.jointplot import JointPlot

X = np.random.rand(100, 2)
y = np.random.rand(100)

viz = JointPlot(columns=[0, 1])

# here, fit_transform is just fit
viz.fit(X=X, y=y)
viz.show()
```
![image](https://user-images.githubusercontent.com/18686697/97182885-5fd48680-179d-11eb-8db7-e2eebc54b100.png)

**Dataset**
No. 

**Expected behavior**
There should be a heatmap to color the samples by the values in `y` as in the PCA case. 

![image](https://user-images.githubusercontent.com/18686697/97187357-a973a000-17a2-11eb-8628-eee182d39547.png)

**Traceback**

```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - OS: Debian10
 - Python Version 3.7
 - Yellowbrick Version 1.2

**Additional context**

**Comment by bbengfort** [comment] 2020-10-26 15:35
Hello, @ZhiliangWu thank you for using Yellowbrick - we're glad that you're using a number of our visualizers including PCA and the JointPlot visualizer. Technically, however, this is not a bug - the JointPlot visualizer does not currently support or implement target-side colorization. However, I agree with you that this would be an excellent feature for JointPlot in the future. 

Currently, JointPlot has a number of enhancements that are currently ongoing, specified in #728, including the suggestion of colorization by the target type (bullet point 2). I'll add your comments to that issue, but close this one in favor of it. Please feel free to comment in #728 about your use case and we'd welcome a PR from you if you're interested in tackling this!

**Closed by bbengfort** 2020-10-26 15:35 UTC
