### ISSUE TITLE
Estimator Score Visualizers

### ISSUE THREAD

**Issue by bbengfort** [DistrictDataLabs/yellowbrick#44] opened 2016-09-07 01:04 UTC

**Comment by rebeccabilbro** [comment] 2016-09-07 01:30
Implement a base class that will follow an estimator in a pipeline (keep in mind that there could be more than one of these things stacked up along each other). This is _not_ a transformer. It needs to extend `BaseEstimator`, `VisualizerMixin`. We also need to create a `ScoringMixin`. `ScoringMixin` has scoring function that saves the state of the scoring to the class so that we can draw it. This will have:

- `fit` 
- `predict`
- `score`
- `draw`

Need to think how we'll access the model from `ScoreVisualizer`. Best option is to have it be instantiated with a model form - this makes sense because we would call fit down into the estimator. The trick will be that the visual pipeline needs to know not to run fit twice.

**Comment by rebeccabilbro** [comment] 2016-10-01 20:12
@bbengfort ok, preliminary implementation here: https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/base.py#L104

**Comment by rebeccabilbro** [comment] 2016-10-02 14:57
ClassifierScoreVisualizers:
 - [ClassificationReport](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L48)
 - [ROCAUC](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L112)

RegressionScoreVisualizers:
 - [PredictionError](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L44)
 - [ResidualsPlot](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/regressor.py#L93)

**Comment by bbengfort** [comment] 2016-10-08 00:59
@rebeccabilbro ok I took a look at these, and things are looking great! There are a few things that we should resolve/discuss:

- [ ] decide on [self.classes](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/classifier.py#L66) or [self.classes_](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/features/pcoords.py#L86) - I guess I was thinking we'd act a bit more like Scikit-Learn; I'm open to other opinions. 

- [ ]

**Comment by rebeccabilbro** [comment] 2016-10-08 11:07
@bbengfort have addressed the first two checkboxes in commits [d57102c](https://github.com/DistrictDataLabs/yellowbrick/commit/d57102cd07b51781e9ff8b382268c2bc94bad2e6) and  [76d2d1f](https://github.com/DistrictDataLabs/yellowbrick/commit/76d2d1f5f9fca25a64220e3a83a804a12d8a6732)

Will tackle the third in the next sprint. 

As for the 4th, I've clarified the difference in base.py [here](https://github.com/DistrictDataLabs/yellowbrick/blob/develop/yellowbrick/base.py#L122). Essentially the main difference is that `ScoreVisualizer` takes a fitted model and `ModelVisualizer` takes a model form.

**Comment by rebeccabilbro** [comment] 2016-10-08 11:09
Marking as complete, with the understanding that issue #62 will resolve the fig/ax hook question that came up in the design of this class.

**Closed** 2016-10-08 11:09 UTC
Labels: level: intermediate, priority: high, type: feature
