### ISSUE TITLE
ClassPredictionError  compatibility with  RidgeClassifier

### ISSUE THREAD

**Issue by maajdl** [DistrictDataLabs/yellowbrick#1060] opened 2020-04-21 10:15 UTC
Hello,

I could not get  ClassPredictionError  working with  RidgeClassifier.
No idea why.
Would there be  a way to have this possibility?

Thanks,

Michel

**Comment by lwgray** [comment] 2020-04-21 10:20
@maajdl Please fill out the information below as best you can.

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**

```python
# Steps to reproduce the behavior (code snippet):
# Should include imports, dataset loading, and execution
# Add the traceback below
```

**Dataset**
Did you use a specific dataset to produce the bug? Where can we access it?

**Expected behavior**
A clear and concise description of what you expected to happen.

**Traceback**

```
If applicable, add the traceback from the exception.
```

**Desktop (please complete the following information):**
 - OS: [e.g. macOS]
 - Python Version [e.g. 2.7, 3.6, miniconda]
 - Yellowbrick Version [e.g. 0.7]

**Additional context**
Add any other context about the problem here.

**Comment by maajdl** [comment] 2020-04-21 12:16
Very sorry, 

I tested it on an example from the docs,  originally for an random forest, and it does work.
I must have a problem in my own application.

Regards,

Michel
___________________________________________________________________________________________
This test below works perfectly:

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import RidgeClassifier
from yellowbrick.classifier import ClassPredictionError


# Create classification dataset
X, y = make_classification(
    n_samples=1000, n_classes=5, n_informative=3, n_clusters_per_class=1,
    random_state=36,
)

classes = ["apple", "kiwi", "pear", "banana", "orange"]

# Perform 80/20 training/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,
                                                    random_state=42)
# Instantiate the classification model and visualizer
visualizer = ClassPredictionError(
    RidgeClassifier(random_state=42), classes=classes
)

# Fit the training data to the visualizer
visualizer.fit(X_train, y_train)

# Evaluate the model on the test data
visualizer.score(X_test, y_test)

# Draw visualization
visualizer.show()

**Comment by rebeccabilbro** [comment] 2020-06-03 16:09
Looks like we can mark this resolved and close this out; thanks for checking out Yellowbrick @maajdl!

**Closed by rebeccabilbro** 2020-06-03 16:09 UTC
