### ISSUE TITLE
Value error too many values to unpack for yellowbrick examples regression notebook

### ISSUE THREAD

**Issue by bhishanpdl** [DistrictDataLabs/yellowbrick#965] opened 2019-09-08 15:48 UTC
I was learning the use of yellowbrick library using the given examples.

When I try to run the notebook `yellowbrick/examples/regression.ipynb`

The code:
```
# Use Yellowbrick to load the concrete dataset
X, y = load_concrete()
```

Gives the error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-6136d8ad4058> in <module>()
      1 # Use Yellowbrick to load the concrete dataset
----> 2 X, y = load_concrete()
      3 
      4 # Create the train and test data
      5 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

ValueError: too many values to unpack (expected 2)
```

How to fix the error?

**Comment by lwgray** [comment] 2019-09-08 22:41
Hi @bhishanpdl Thank you for using Yellowbrick.    I am not able to reproduce your error.  Could provide more detail by responding to the statements below?

1.  What 'import' statements did you use

2.  please complete the following information
 - OS: [e.g. macOS]
 - Python Version [e.g. 2.7, 3.6, miniconda]
 - Yellowbrick Version [e.g. 0.7]

**Comment by bbengfort** [comment] 2019-10-06 12:49
@bhishanpdl since this question is more than a month old and we can't reproduce the error, I'm going to close the issue. However, if you would like to respond to @lwgray with the Yellowbrick version you're on, then we'd be happy to reopen it! Thanks for using Yellowbrick!

**Closed by bbengfort** 2019-10-06 12:49 UTC
Labels: type: question
