### ISSUE TITLE
ValueError from multiclass data shapes in ParallelCoordinates and RadViz

### ISSUE THREAD

**Issue by JohannesBuchner** [DistrictDataLabs/yellowbrick#650] opened 2018-10-31 20:52 UTC
**Describe the bug**

I am having trouble using ParallelCoordinates and RadViz with a multi-class dataset.

**To Reproduce**

```python
numpy.random.seed(1)
XT = numpy.arange(1000).reshape((-1,2))
YT = numpy.random.randint(6, size=len(XT))*10
print(XT.shape, XT.dtype, YT.shape, YT.dtype)
visualizer = ParallelCoordinates(sample=0.05, shuffle=True, fast=True)
visualizer.fit_transform(XT, YT)
visualizer.poof(outpath='viz_feature_parallel_coords.pdf', bbox_inches='tight')

visualizer = RadViz()
visualizer.fit_transform(XT, YT)
visualizer.poof(outpath='viz_feature_radviz.pdf', bbox_inches='tight')
```

**Dataset**
The dataset has 6 classes and 500 instances here.

**Traceback**

```
(500, 2) int64 (500,) int64
Traceback (most recent call last):
  File "../train_randomforest.py", line 124, in <module>
    visualizer.fit_transform(XT, YT)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/sklearn/base.py", line 465, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/pcoords.py", line 376, in fit
    return super(ParallelCoordinates, self).fit(X, y, **kwargs)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/base.py", line 224, in fit
    self.draw(X, y, **kwargs)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/pcoords.py", line 396, in draw
    return self.draw_classes(X, y, **kwargs)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/pcoords.py", line 485, in draw_classes
    color=self._colors[label], alpha=alpha, **kwargs
  File "/usr/lib64/python2.7/site-packages/matplotlib/__init__.py", line 1717, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_axes.py", line 1372, in plot
    for line in self._get_lines(*args, **kwargs):
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 404, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 384, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "/usr/lib64/python2.7/site-packages/matplotlib/axes/_base.py", line 243, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (84,) and (6,)
```

The RadViz part gives:
```
/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/radviz.py:212: RuntimeWarning: invalid value encountered in divide
  xy   = (s * row_).sum(axis=0) / row.sum()
Traceback (most recent call last):
  File "../train_randomforest.py", line 127, in <module>
    visualizer.fit_transform(XT, YT)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/sklearn/base.py", line 465, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/base.py", line 224, in fit
    self.draw(X, y, **kwargs)
  File "/home/jbuchner/.local/lib/python2.7/site-packages/yellowbrick/features/radviz.py", line 213, in draw
    kls = self.classes_[y[i]]

```

**Desktop (please complete the following information):**
 - OS: Linux
 - Python Version 2.7
 - Yellowbrick Version 0.8

What am I doing wrong?

**Comment by bbengfort** [comment] 2018-10-31 21:06
Hi @JohannesBuchner - I'm about to head out, but I have a suspicion, can you try:

```python
visualizer = ParallelCoordinates(features=features,
	sample=0.05, shuffle=True, fast=True, classes=[0, 10, 20, 30, 40, 50])
```

And see what that does?

**Comment by bbengfort** [comment] 2018-11-02 14:19
@JohannesBuchner - so there is a known issue that we've been struggling to deal with, which is handling the type of the target (though both ParallelCoordinates and RadViz are earlier visualizers, so potentially there is an easy fix). 

Basically, the issue is that `y` can either be strings (e.g. if you convert YT to a string array) that are then label encoded, otherwise, they have to be index values, e.g. [0,5] rather than [0,60,10]. The reason for this is because we need strings for drawing on matplotlib, but we can be given either strings or ints for machine learning purposes; we, therefore, convert the values to a string, but use `np.unique` rather than a `dict`, and this is the source of the index error. 

In the end, if you convert `YT = numpy.random.randint(6, size=len(XT))*10` to `YT = numpy.random.randint(6, size=len(XT))` the visualizers work, but if you feel that we need to be able to support targets like the ones you specified, we could dig into it further.

**Comment by JohannesBuchner** [comment] 2018-11-02 17:22
At the moment I am trying to find an example how it is supposed to work, so I can shoehorn my problem into it.
I tried converting to strings:

```
numpy.random.seed(1)
XT = numpy.arange(20).reshape((-1,2))
YT = (numpy.random.randint(3, size=len(XT))*10).astype('S3').tolist()
classes = ['0', '10', '20']
print('y:', YT)
print('classes:', classes)

visualizer = RadViz(classes = classes)
visualizer.fit_transform(XT, YT)
visualizer.poof(outpath='viz_feature_radviz.pdf', bbox_inches='tight')
plt.close('all')

visualizer = ParallelCoordinates(classes=classes, sample=0.05, shuffle=True, fast=True)
visualizer.fit_transform(XT, YT)
visualizer.poof(outpath='viz_feature_parallel_coords.pdf', bbox_inches='tight')
plt.close('all')
```

But it wants y to be nan-testable:
```
y: [b'10', b'0', b'0', b'10', b'10', b'0', b'0', b'10', b'0', b'10']
classes: ['0', '10', '20']
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
testviz.py in <module>()
     11 
     12 visualizer = RadViz(classes = classes)
---> 13 visualizer.fit_transform(XT, YT)
     14 visualizer.poof(outpath='viz_feature_radviz.pdf', bbox_inches='tight')
     15 plt.close('all')

/home/user/.local/lib64/python3.5/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    463         else:
    464             # fit method of arity 2 (supervised transformation)
--> 465             return self.fit(X, y, **fit_params).transform(X)
    466 
    467 

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/features/base.py in fit(self, X, y, **kwargs)
    222 
    223         # Draw the instances
--> 224         self.draw(X, y, **kwargs)
    225 
    226         # Fit always returns self.

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/features/radviz.py in draw(self, X, y, **kwargs)
    174         # Clean out nans and warn that the user they aren't plotted
    175         nan_warnings.warn_if_nans_exist(X)
--> 176         X, y = nan_warnings.filter_missing(X, y)
    177 
    178         # Get the shape of the data

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/utils/nan_warnings.py in filter_missing(X, y)
     40     """
     41     if y is not None:
---> 42         return filter_missing_X_and_y(X, y)
     43     else:
     44         return X[~np.isnan(X).any(axis=1)]

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/utils/nan_warnings.py in filter_missing_X_and_y(X, y)
     47 def filter_missing_X_and_y(X, y):
     48     """Remove rows from X and y where either contains nans."""
---> 49     y_nans = np.isnan(y)
     50     x_nans = np.isnan(X).any(axis=1)
     51     unioned_nans = np.logical_or(x_nans, y_nans)

TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

**Comment by JohannesBuchner** [comment] 2018-11-02 17:45
Using string classes with indexing integers is also giving me issues:

```
numpy.random.seed(2)
XT = numpy.arange(20).reshape((-1,2))
YT = numpy.random.randint(3, size=len(XT))
classes = [0, 1, 2]
classes = ['orange', 'blue', 'yellow']
print('y:', YT)
print('classes:', classes)

visualizer = RadViz(classes = classes)
visualizer.fit_transform(XT, YT)
```

```
y: [0 1 0 2 2 0 2 1 1 2]
classes: ['orange', 'blue', 'yellow']
/home/user/.local/lib64/python3.5/site-packages/yellowbrick/features/radviz.py:212: RuntimeWarning: invalid value encountered in true_divide
  xy   = (s * row_).sum(axis=0) / row.sum()
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/lib64/python3.5/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    165     try:
--> 166         rgba = _colors_full_map.cache[c, alpha]
    167     except (KeyError, TypeError):  # Not in cache, or unhashable.

KeyError: (0.4470588235294118, None)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
/mnt/data/daten/Master/home/Downloads/lsst-challenge/testviz.py in <module>()
     12 
     13 visualizer = RadViz(classes = classes)
---> 14 visualizer.fit_transform(XT, YT)
     15 # ValueError: Invalid RGBA argument: 0.4470588235294118
     16 

/home/user/.local/lib64/python3.5/site-packages/sklearn/base.py in fit_transform(self, X, y, **fit_params)
    463         else:
    464             # fit method of arity 2 (supervised transformation)
--> 465             return self.fit(X, y, **fit_params).transform(X)
    466 
    467 

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/features/base.py in fit(self, X, y, **kwargs)
    222 
    223         # Draw the instances
--> 224         self.draw(X, y, **kwargs)
    225 
    226         # Fit always returns self.

/home/user/.local/lib64/python3.5/site-packages/yellowbrick/features/radviz.py in draw(self, X, y, **kwargs)
    222             self.ax.scatter(
    223                 to_plot[kls][0], to_plot[kls][1], color=colors[kls],
--> 224                 label=str(kls), alpha=self.alpha, **kwargs
    225             )
    226 

/usr/lib64/python3.5/site-packages/matplotlib/__init__.py in inner(ax, *args, **kwargs)
   1853                         "the Matplotlib list!)" % (label_namer, func.__name__),
   1854                         RuntimeWarning, stacklevel=2)
-> 1855             return func(ax, *args, **kwargs)
   1856 
   1857         inner.__doc__ = _add_data_doc(inner.__doc__,

/usr/lib64/python3.5/site-packages/matplotlib/axes/_axes.py in scatter(self, x, y, s, c, marker, cmap, norm, vmin, vmax, alpha, linewidths, verts, edgecolors, **kwargs)
   4318                 offsets=offsets,
   4319                 transOffset=kwargs.pop('transform', self.transData),
-> 4320                 alpha=alpha
   4321                 )
   4322         collection.set_transform(mtransforms.IdentityTransform())

/usr/lib64/python3.5/site-packages/matplotlib/collections.py in __init__(self, paths, sizes, **kwargs)
    925         """
    926 
--> 927         Collection.__init__(self, **kwargs)
    928         self.set_paths(paths)
    929         self.set_sizes(sizes)

/usr/lib64/python3.5/site-packages/matplotlib/collections.py in __init__(self, edgecolors, facecolors, linewidths, linestyles, capstyle, joinstyle, antialiaseds, offsets, transOffset, norm, cmap, pickradius, hatch, urls, offset_position, zorder, **kwargs)
    134         self._hatch_color = mcolors.to_rgba(mpl.rcParams['hatch.color'])
    135         self.set_facecolor(facecolors)
--> 136         self.set_edgecolor(edgecolors)
    137         self.set_linewidth(linewidths)
    138         self.set_linestyle(linestyles)

/usr/lib64/python3.5/site-packages/matplotlib/collections.py in set_edgecolor(self, c)
    763         """
    764         self._original_edgecolor = c
--> 765         self._set_edgecolor(c)
    766 
    767     def set_edgecolors(self, c):

/usr/lib64/python3.5/site-packages/matplotlib/collections.py in _set_edgecolor(self, c)
    744         except AttributeError:
    745             pass
--> 746         self._edgecolors = mcolors.to_rgba_array(c, self._alpha)
    747         if set_hatch_color and len(self._edgecolors):
    748             self._hatch_color = tuple(self._edgecolors[0])

/usr/lib64/python3.5/site-packages/matplotlib/colors.py in to_rgba_array(c, alpha)
    265     result = np.empty((len(c), 4), float)
    266     for i, cc in enumerate(c):
--> 267         result[i] = to_rgba(cc, alpha)
    268     return result
    269 

/usr/lib64/python3.5/site-packages/matplotlib/colors.py in to_rgba(c, alpha)
    166         rgba = _colors_full_map.cache[c, alpha]
    167     except (KeyError, TypeError):  # Not in cache, or unhashable.
--> 168         rgba = _to_rgba_no_colorcycle(c, alpha)
    169         try:
    170             _colors_full_map.cache[c, alpha] = rgba

/usr/lib64/python3.5/site-packages/matplotlib/colors.py in _to_rgba_no_colorcycle(c, alpha)
    217         # float)` and `np.array(...).astype(float)` all convert "0.5" to 0.5.
    218         # Test dimensionality to reject single floats.
--> 219         raise ValueError("Invalid RGBA argument: {!r}".format(orig_c))
    220     # Return a tuple to prevent the cached value from being modified.
    221     c = tuple(c.astype(float))

ValueError: Invalid RGBA argument: 0.4470588235294118

```
seed(1) works accidentally, because only generates instances from 2 classes.

**Comment by bbengfort** [comment] 2018-11-02 19:00
Ok, there is definitely a bug here, which I'll open up a new issue for, since it is separate from the problem you brought up in this issue. Could you tell me what version of matplotlib you're using?

Right now a quick fix is as follows:

```python
visualizer = RadViz(classes=classes, color=['r', 'g', 'b'])
```

Let me know if that helps!

**Comment by bbengfort** [comment] 2018-11-02 19:05
Well, this is strange, the following code doesn't generate the bug, though I expected it to:

```python

from yellowbrick.features import RadViz 
from sklearn.datasets import make_classification 


X, y = make_classification(n_classes=3, n_informative=4) 

oz = RadViz(classes=["red", "green", "blue"]) 
oz.fit_transform(X, y) 
oz.poof()
```

**Comment by bbengfort** [comment] 2018-11-02 19:09
@JohannesBuchner in your example, this is the value of `_colors`:

```python
{
    'red': (0.00784313725490196, 0.4470588235294118, 0.6352941176470588), 
    'green': (0.6235294117647059, 0.7647058823529411, 0.4666666666666667), 
    'blue': (0.792156862745098, 0.043137254901960784, 0.011764705882352941)
}
```

But this is the value of `to_plot`:

```python
[[nan, 0.0, 0.0], [nan, 6.123233995736766e-17, 6.123233995736766e-17]]
```

I wonder if those `nan` values are causing problems?

**Comment by Naba7** [comment] 2019-02-13 04:27
Can I be assigned this issue?

**Comment by rebeccabilbro** [comment] 2019-04-15 00:44
@JohannesBuchner @bbengfort &mdash; can this issue be closed?

**Comment by naresh-bachwani** [comment] 2019-06-15 12:21
As @bbengfort mentioned [above](https://github.com/DistrictDataLabs/yellowbrick/issues/650#issuecomment-435395082) these visualizers are meant to handle index values for target i.e. target should be [0,1,2,..] rather than [0, 10,20,....]. This is because these functions use the values of target to access the list(like `self.classes_[y[i]]`).

The issue with colors has been handled(probably in matplotlib as I see no merge to RadViz after this issue was opened).

@lwgray this can be closed if support for targets with higher increments is not required.

**Closed** 2019-06-28 11:06 UTC
Labels: type: bug
